//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_recibo
    {
        public int iddetalle { get; set; }
        public int idrecibo { get; set; }
        public Nullable<int> idreserva { get; set; }
        public Nullable<int> idgasto { get; set; }
        public Nullable<decimal> porcentajegasto { get; set; }
        public int montosoles { get; set; }
        public Nullable<int> usuariocreacion { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
    
        public virtual Gasto Gasto { get; set; }
        public virtual Recibo Recibo { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
