//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gasto()
        {
            this.Detalle_recibo = new HashSet<Detalle_recibo>();
        }
    
        public int idgasto { get; set; }
        public string Descripcion { get; set; }
        public int IdProveedor { get; set; }
        public System.DateTime FechaGasto { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int TipoGasto { get; set; }
        public int TipoCalculo { get; set; }
        public int IdCondominio { get; set; }
        public int IdTorre { get; set; }
        public int IdDepartamento { get; set; }
        public Nullable<decimal> montosoles { get; set; }
        public Nullable<int> usuariocreacion { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
    
        public virtual Condominio Condominio { get; set; }
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_recibo> Detalle_recibo { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Torre Torre { get; set; }
    }
}
