//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recibo()
        {
            this.Detalle_recibo = new HashSet<Detalle_recibo>();
        }
    
        public int idrecibo { get; set; }
        public System.DateTime FechaRecibo { get; set; }
        public string Periodo { get; set; }
        public decimal MontoTotalSoles { get; set; }
        public int IdPropietario { get; set; }
        public int IdInquilino { get; set; }
        public int IdDepartamento { get; set; }
        public int IdEstadoRecibo { get; set; }
        public Nullable<int> usuariocreacion { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_recibo> Detalle_recibo { get; set; }
        public virtual EstadoRecibo EstadoRecibo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
