//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoArea()
        {
            this.AreaComun = new HashSet<AreaComun>();
        }
    
        public int idtipoarea { get; set; }
        public string Nombre { get; set; }
        public string TipoReserva { get; set; }
        public Nullable<System.TimeSpan> HoraApertura { get; set; }
        public Nullable<System.TimeSpan> HoraCierre { get; set; }
        public int CantidadMaxima { get; set; }
        public Nullable<int> usuariocreacion { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaComun> AreaComun { get; set; }
    }
}
