//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Torre()
        {
            this.Departamento = new HashSet<Departamento>();
            this.Gasto = new HashSet<Gasto>();
        }
    
        public int idtorre { get; set; }
        public string Nombre { get; set; }
        public int IdCondominio { get; set; }
        public Nullable<int> usuariocreacion { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<int> usuariomodificacion { get; set; }
        public Nullable<System.DateTime> fechamodificacion { get; set; }
    
        public virtual Condominio Condominio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departamento> Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
    }
}
